BIGMVC_project/Controllers/HrsController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BIGMVC_project.Models;
using System.Xml.Linq;
//using HR_Management.Data;
//using HR_Management.Model;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HR_Management.Controllers
{
	public class HrsController : Controller
	{
		private readonly MyDbContext _context;

		public HrsController(MyDbContext context)
		{
			_context = context;
		}
		public IActionResult Dashboard()
		{

			var totalHR = _context.Hrs.Count();
			var totalEmployees = _context.Employees.Count();
			var totalManagers = _context.Managers.Count();
			var totalDepartments = _context.Departments.Count();
			var tasks = _context.Missions.Include(m => m.Employee).ToList();

			ViewBag.Tasks = tasks;
			ViewBag.TotalTasks = tasks.Count();
			ViewBag.TotalHR = totalHR;
			ViewBag.TotalEmployees = totalEmployees;
			ViewBag.TotalManagers = totalManagers;
			ViewBag.TotalDepartments = totalDepartments;

			var departmentEmployeeCount = _context.Employees
				.GroupBy(e => e.Department.Name)
				.Select(group => new
				{
					DepartmentName = group.Key,
					EmployeeCount = group.Count()
				})
				.ToList();

			ViewBag.DepartmentEmployeeCount = departmentEmployeeCount;

			return View();
		}




		public IActionResult LeaveRequests()
		{
			var allLeaveRequests = _context.LeaveRequests.ToList();
			return View(allLeaveRequests);
		}

		public IActionResult Feedback()
		{
			var feedbackList = _context.Feedbacks.ToList();
			return View(feedbackList);
		}


		[HttpPost]
		public async Task<IActionResult> SubmitFeedback(Feedback feedback)
		{
			if (ModelState.IsValid)
			{
				feedback.SubmittedAt = DateTime.Now;
				_context.Feedbacks.Add(feedback);
				await _context.SaveChangesAsync();
				TempData["Success"] = "Success!";
				return RedirectToAction("Feedback");
			}

			return View("Feedback", feedback);
		}


		[HttpPost]
		public async Task<IActionResult> DeleteFeedback(int id)
		{
			var feedback = await _context.Feedbacks.FindAsync(id);
			if (feedback != null)
			{
				_context.Feedbacks.Remove(feedback);
				await _context.SaveChangesAsync();
			}

			return RedirectToAction("Feedback");
		}


		[HttpPost]
		public async Task<IActionResult> ReplyToFeedback(int id, string reply)
		{
			var feedback = await _context.Feedbacks.FindAsync(id);
			if (feedback == null)
			{
				return NotFound();
			}

			feedback.ReplyMessage = reply;
			_context.Feedbacks.Update(feedback);
			await _context.SaveChangesAsync();

			TempData["Success"] = "Success!";
			return RedirectToAction("Feedback");
		}


		//public IActionResult ContactUs()
		//{
		//    return View(new Feedback());
		//}


		[HttpPost]
		public IActionResult SendFeedback(Feedback feedback)
		{
			if (ModelState.IsValid)
			{
				feedback.SubmittedAt = DateTime.Now;
				_context.Feedbacks.Add(feedback);
				_context.SaveChanges();
				return RedirectToAction("ContactUs");
			}

			return View("ContactUs", feedback);
		}


		public IActionResult AddManager()
		{
			var departments = _context.Departments.ToList(); // assuming you're using Entity Framework
			ViewBag.Departments = departments;
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> AddManager(Manager model, IFormFile profilePicture)
		{
			// Check if email is already taken
			if (_context.Managers.Any(m => m.Email == model.Email))
			{
				ModelState.AddModelError("Email", "This email is already in use.");
				return View(model);
			}

			// Check if the model is valid
			if (!ModelState.IsValid)
			{
				return View(model); // Return the view with validation errors if the model is invalid
			}

			// Handle profile picture upload
			if (profilePicture != null && profilePicture.Length > 0)
			{
				var allowedExtensions = new[] { ".jpg", ".jpeg", ".png" };
				var fileExtension = Path.GetExtension(profilePicture.FileName).ToLower();
				if (!allowedExtensions.Contains(fileExtension))
				{
					ModelState.AddModelError("ProfilePicture", "Invalid image format. Only .jpg, .jpeg, and .png are allowed.");
					return View(model);
				}

				// Clean the filename to avoid invalid characters
				var fileName = Path.GetFileNameWithoutExtension(profilePicture.FileName);
				var cleanedFileName = Path.Combine(fileName + fileExtension); // Add extension back
				var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "managers", cleanedFileName);
				var directoryPath = Path.GetDirectoryName(filePath);

				if (!Directory.Exists(directoryPath))
				{
					Directory.CreateDirectory(directoryPath);
				}

				using (var stream = new FileStream(filePath, FileMode.Create))
				{
					await profilePicture.CopyToAsync(stream);
				}

				model.Image = cleanedFileName;
			}

			// Add the manager to the context
			_context.Managers.Add(model);
			await _context.SaveChangesAsync();

			// Redirect to a relevant action (for example, the details page of the new manager)
			return RedirectToAction("ManagerDetails", new { id = model.Id });
		}

		// GET: Hrs/ManagerDetails/5
		[HttpGet("manager/details/{id}")]
		public IActionResult ManagerDetails(int id)
		{
			var manager = _context.Managers
				.Include(m => m.Department)
				.FirstOrDefault(m => m.Id == id);

			if (manager == null)
			{
				return NotFound();
			}

			return RedirectToAction("Manager");
		}
		public IActionResult ExportLeaveRequestsToPDF()
		{
			var leaveRequests = _context.LeaveRequests.ToList();

			var pdfStream = new MemoryStream();

			var document = new Document(PageSize.A4);
			var writer = PdfWriter.GetInstance(document, pdfStream);

			document.Open();

			var font = FontFactory.GetFont("Arial", 20, Font.BOLD);
			Paragraph title = new Paragraph("Leave Requests", font)
			{
				Alignment = Element.ALIGN_CENTER
			};

			title.SpacingAfter = 20f;

			document.Add(title);

			document.Add(new Paragraph(" "));

			var table = new PdfPTable(5) { WidthPercentage = 100 };
			table.SpacingBefore = 20f;

			table.AddCell("Employee ID");
			table.AddCell("Start Date");
			table.AddCell("End Date");
			table.AddCell("Reason");
			table.AddCell("Status");

			foreach (var request in leaveRequests)
			{
				table.AddCell(request.EmployeeId.ToString());
				table.AddCell(request.StartDate.ToShortDateString());
				table.AddCell(request.EndDate.ToShortDateString());
				table.AddCell(request.Reason);
				table.AddCell(request.LeaveRequestsStatusEnum);
			}

			document.Add(table);

			document.Close();

			return File(pdfStream.ToArray(), "application/pdf", "LeaveRequests.pdf");
		}

		public IActionResult DepartmentService()
		{
			return View();
		}
		//////////////////////////////////////
		/////////////////////////////////////////////
		/////////////////////////////////////////////
		///// GET: Hrs
		public async Task<IActionResult> Index()
		{
			return View(await _context.Hrs.ToListAsync());
		}

		// GET: Hrs/Details/5
		public async Task<IActionResult> HRDetails(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var hr = await _context.Hrs
				.FirstOrDefaultAsync(m => m.Id == id);
			if (hr == null)
			{
				return NotFound();
			}

			return View(hr);
		}

		// GET: Hrs/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Hrs/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Name,Email,PasswordHash,Image")] Hr hr)
		{
			if (ModelState.IsValid)
			{
				_context.Add(hr);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(hr);
		}

		// GET: Hrs/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var hr = await _context.Hrs.FindAsync(id);
			if (hr == null)
			{
				return NotFound();
			}
			return View(hr);
		}

		// POST: Hrs/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,PasswordHash,Image")] Hr hr)
		{
			if (id != hr.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(hr);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!HrExists(hr.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(hr);
		}

		// GET: Hrs/Delete/5
		// GET: Hrs/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var hr = await _context.Hrs
				.FirstOrDefaultAsync(m => m.Id == id);
			if (hr == null)
			{
				return NotFound();
			}

			return View(hr);
		}

		// GET: Hrs/Create
		public IActionResult Createe()
		{
			return View(); // This will display the Create.cshtml form
		}

		// POST: Hrs/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Createe([Bind("Name,Email,PasswordHash,Image")] Hr hr)
		{
			if (ModelState.IsValid)
			{
				_context.Add(hr);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index)); // Redirect to HR list after creation
			}
			return View(hr); // Re-display form with validation errors
		}

		// POST: Hrs/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var hr = await _context.Hrs.FindAsync(id);
			if (hr != null)
			{
				_context.Hrs.Remove(hr);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool HrExists(int id)
		{
			return _context.Hrs.Any(e => e.Id == id);
		}

		// Export HR data to PDF
		public IActionResult ExportHRToPDF()
		{
			var HR = _context.Hrs.ToList();

BIGMVC_project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
	<link rel="icon" type="image/png" href="../assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>Light Bootstrap Dashboard - Free Bootstrap 4 Admin Dashboard by Creative Tim</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

	<!-- Fonts and icons -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />

	<!-- CSS Files -->
	<link href="~/css/bootstrap.min.css" rel="stylesheet" />
	<link href="~/css/light-bootstrap-dashboard.css?v=2.0.0" rel="stylesheet" />

	<!-- Demo CSS (Just for demo purpose, don't include in your project) -->
	<link href="../assets/css/demo.css" rel="stylesheet" />

	<script src="/lib/chart/chart.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

	<style>
		body {
			margin: 0;
			font-family: "Open Sans", sans-serif;
			font-size: 1rem;
			font-weight: 400;
			line-height: 1.5;
			color: #6C7293;
			background-color: white;
			-webkit-text-size-adjust: 100%;
			-webkit-tap-highlight-color: rgba(0, 0, 0, 0);
		}

		.sidebar-wrapper {
			background-color: rgba(21, 34, 43, 0.85) !important;
		}


	</style>
</head>

<body>
	<div " class="wrapper">
		<div class="sidebar" data-image="@Url.Content("~/image/HRoot_Logo-removebg-preview.png")">
			<div class="sidebar-wrapper">
				<div class="logo">
					<h1 class="sitename"><img src="~/image/HRoot_Logo-removebg-preview.png" style="max-height:46px !important" alt="Alternate Text" /></h1>
				</div>
				<ul class="nav">
					<li>
						<a class="nav-link" href="@Url.Action("LeaveRequests", "Hrs")">
							<i class="fas fa-table"></i>
							<p>Leave Requests</p>
						</a>
					</li>
					<li>
						<a class="nav-link" href="@Url.Action("Feedback", "Hrs")">
							<i class="fas fa-comment"></i>
							<p>Feedback</p>
						</a>
					</li>
					<li>
						<a class="nav-link" href="@Url.Action("Index", "Hrs")">
							<i class="fas fa-users"></i>
							<p>Hr Team</p>
						</a>
					</li>
					<li class="nav-item active">
						<a class="nav-link" href="@Url.Action("Index", "Departments")">
							<i class="fas fa-building"></i>
							<p>Department</p>
						</a>
					</li>
					<li>
						<a class="nav-link" href="@Url.Action("Manager", "Hrs")">
							<i class="fas fa-user"></i>
							<p>Managers</p>
						</a>
					</li>
					<li>
						<a class="nav-link" href="@Url.Action("Employee", "Hrs")">
							<i class="fas fa-users"></i>
							<p>Employees</p>
						</a>
					</li>
					<li>
						<a class="nav-link" href="@Url.Action("Evaluation", "Hrs")">
							<i class="fas fa-star"></i>
							<p>Evaluation</p>
						</a>
					</li>
					<li>
						<a class="nav-link" asp-action="Logout" asp-controller="Manager">
							<i class="fas fa-sign-out-alt"></i>
							<p>Logout</p>
						</a>
					</li>
				</ul>
			</div>
		</div>

		<div class="main-panel">
			<div class="container">
			@RenderBody()
			</div>
		</div>
	</div>

	<!-- JS Files -->
	<script src="../assets/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
	<script src="../assets/js/core/popper.min.js" type="text/javascript"></script>
	<script src="../assets/js/core/bootstrap.min.js" type="text/javascript"></script>
	<script src="../assets/js/plugins/bootstrap-switch.js"></script>
	<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
	<script src="../assets/js/plugins/chartist.min.js"></script>
	<script src="../assets/js/plugins/bootstrap-notify.js"></script>
	<script src="../assets/js/light-bootstrap-dashboard.js?v=2.0.0" type="text/javascript"></script>
	<script src="../assets/js/demo.js"></script>
</body>
</html>

BIGMVC_project/Views/Shared/_LayoutGen.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - BIGMVC_project</title>



	<link rel="apple-touch-icon" sizes="76x76" href="~/Images/apple-icon.png">
	<link rel="icon" type="image/png" href="~/Images/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>Light Bootstrap Dashboard - Free Bootstrap 4 Admin Dashboard by Creative Tim</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
	<!--     Fonts and icons     -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/now-ui-kit/1.3.0/css/now-ui-kit.min.css">

	<!-- CSS Files -->
	<link href="~/css/bootstrap.min.css" rel="stylesheet" />

	<link href="~/css/light-bootstrap-dashboard.css?v=2.0.0" rel="stylesheet" />

	<link href="~/css/demo.css" rel="stylesheet" />


</head>
<div class="sidebar" data-image="../assets/img/sidebar-5.jpg">

	<div class="sidebar-wrapper">
		<div class="logo">
			<a href="http://www.creative-tim.com" class="simple-text">
				<h1 class="sitename"><img src="~/image/HRoot_Logo-removebg-preview.png" style="max-height:46px !important" alt="Alternate Text" /></h1>
			</a>
		</div>
		<ul class="nav">
			<li class="nav-item active">


				@* <a class="nav-link" href="@Url.Action("Dashboard", "EmployeeAttend")"> *@

				@* 	<i class="fa-solid fa-chart-pie"></i> *@
				@* 	<p>Dashboard</p> *@

				@* </a> *@
			</li>
			<li>


				<a class="nav-link" href="@Url.Action("Profile", "EmployeeAttend")">

					<i class="fa-solid fa-user"></i>
					<p>User Profile</p>

				</a>
			</li>
			<li>
				<a class="nav-link" href="@Url.Action("Index", "EmployeeAttend")">

					<i class="fa-solid fa-clipboard-check"></i>
					<p>Attendance</p>

				</a>
			</li>
			<li>
				<a class="nav-link" href="@Url.Action("ViewTasks", "EmployeeAttend")">

					<i class="fa-solid fa-list-check"></i>
					<p>View Tasks</p>

				</a>
			</li>
			<li>
				<a class="nav-link" href="@Url.Action("LeaveRequest", "EmployeeAttend")">
					<i class="fa-solid fa-plane-departure"></i>
					<p>Leave or Vacation</p>

				</a>
			</li>
			@* <li> *@
			@* 	<a class="nav-link" href="@Url.Action("Logout", "EmployeeAttend")"> *@
			@* 		<i class="fa-solid fa-door-open"></i> *@
			@* 		<p>Logout</p> *@

			@* 	</a> *@
			@* </li> *@
			<li>
				<a class="nav-link" asp-action="Logout" asp-controller="Manager">
					<i class="fa fa-sign-out"></i>
					<p>Logout</p>
				</a>
			</li>

		</ul>
	</div>
</div>





<body>
	<main role="main" class="pb-3">
		@RenderBody()
	</main>






	<!--   Core JS Files   -->
	<script src="~/js/jquery.3.2.1.min.js" type="text/javascript"></script>



	<script src="~/js/popper.min.js" type="text/javascript"></script>



	<script src="~/js/bootstrap.min.js" type="text/javascript"></script>



	<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
	<script src="~/js/bootstrap-switch.js"></script>

	<!--  Google Maps Plugin    -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
	<!--  Chartist Plugin  -->
	<script src="~/js/chartist.min.js"></script>

	<!--  Notifications Plugin    -->
	<script src="~/js/bootstrap-notify.js"></script>

	<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
	<script src="~/js/light-bootstrap-dashboard.js?v=2.0.0 " type="text/javascript"></script>

	<!-- Light Bootstrap Dashboard DEMO methods, don't include it in your project! -->
	<script src="~/js/demo.js"></script>

	<script type="text/javascript">
		$(document).ready(function() {
			// Javascript method's body can be found in assets/js/demos.js
			demo.initDashboardPageCharts();

			demo.showNotification();

		});
	</script>



</body>
</html>

BIGMVC_project/Views/Shared/_ManagersLayout1.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
	<link rel="icon" type="image/png" href="../assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>Light Bootstrap Dashboard - Free Bootstrap 4 Admin Dashboard by Creative Tim</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

	<!-- Fonts and icons -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

	<!-- CSS Files -->
	<link href="~/css/bootstrap.min.css" rel="stylesheet" />
	<link href="~/css/light-bootstrap-dashboard.css?v=2.0.0" rel="stylesheet" />

	<!-- Demo CSS (Just for demo purpose, don't include in your project) -->
	<link href="../assets/css/demo.css" rel="stylesheet" />
	<link href="https://cdnjs.cloudflare.com/ajax/libs/now-ui-icons/1.0.1/css/now-ui-icons.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />


	<script src="/lib/chart/chart.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
	@RenderSection("style", required: false)
	<style>
		/* body { */
		/* 	margin: 0; */
		/* 	font-family: "Open Sans", sans-serif; */
		/* 	font-size: 1rem; */
		/* 	font-weight: 400; */
		/* 	line-height: 1.5; */
		/* 	color: #6C7293; */
		/* 	-webkit-text-size-adjust: 100%; */
		/* 	-webkit-tap-highlight-color: rgba(0, 0, 0, 0); */
		/* } */
	</style>
</head>

<body>
	<div class="wrapper">
		<div class="sidebar" data-image="@Url.Content("~/img/sidebar-5.jpg")">
			<div class="sidebar-wrapper">
				<div class="logo">
					<h1 class="sitename"><img src="~/image/HRoot_Logo-removebg-preview.png" style="max-height:46px !important" alt="Alternate Text" /></h1>
				</div>
				<ul class="nav">
					<li>
						<a class="nav-link" asp-action="Show_Employee" asp-controller="Manager">
							<i class="fa fa-user"></i>
							<p>Employee_data</p>
						</a>
					</li>
					<li>
						<a class="nav-link" href="@Url.Action("Addemployee", "Manager")">
							<i class="fa fa-user"></i>
							<p>Add Employee</p>
						</a>
					</li>
					<li>
						<a class="nav-link" asp-action="LeavingR" asp-controller="Manager">
							<i class="fa fa-table"></i>
							<p>
								Time-Off Request
							</p>
						</a>
					</li>
					<li>
						<a class="nav-link" asp-action="Logout" asp-controller="Manager">
							<i class="fa fa-sign-out"></i>
							<p>Logout</p>
						</a>
					</li>
					@* <li> *@
					@* 	<a class="nav-link" asp-action="Profile" asp-controller="Manager"> *@
					@* 		<i class="fa fa-user"></i> *@
					@* 		<p>Profile</p> *@
					@* 	</a> *@
					@* </li> *@
				</ul>
			</div>
		</div>
		<div class="main-panel">
			<!-- Navbar -->
			<div class="container">
				@RenderBody()
				</main>
			</div>
		</div>
		<!-- Content End -->
	</div>

	<!-- JS Files -->
	<script src="../assets/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
	<script src="../assets/js/core/popper.min.js" type="text/javascript"></script>
	<script src="../assets/js/core/bootstrap.min.js" type="text/javascript"></script>
	<script src="../assets/js/plugins/bootstrap-switch.js"></script>
	<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
	<script src="../assets/js/plugins/chartist.min.js"></script>
	<script src="../assets/js/plugins/bootstrap-notify.js"></script>
	<script src="../assets/js/light-bootstrap-dashboard.js?v=2.0.0" type="text/javascript"></script>
	<script src="../assets/js/demo.js"></script>

	<script type="text/javascript">
		$(document).ready(function() {
			demo.initDashboardPageCharts();
			demo.showNotification();
		});
	</script>
	@RenderSection("scripts", required: false);
</body>
</html>